steps:
  - name: node:8.19
    entrypoint: npm
    args: ["install"]
  - name: node:8.19
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "MY_SECRET_KEY=${_MY_SECRET_KEY}"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY
